language: csharp
solution: Algorithms.sln
install:
  - nuget restore Algorithms.sln
  - nuget install NUnit.Console -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild Algorithms.sln /p:Configuration=Debug
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./AlgorithmsTests/bin/Debug/AlgorithmsTests.dll