version: 1.1.{build}
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: M6D0gHEqDI6J/zl93x+AVr6WVxzEviMR6xILmZ8sYqEy5GiumoMtgjljg+opDObB
before_build:
  - nuget restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory tools
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - nuget install coveralls.net -Version 0.6.0 -OutputDirectory tools
build:
  project: Algorithms.sln 
  verbosity: minimal
after_test: 
    - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:.\tools\NUnit.Runners.2.6.4\tools\nunit-console.exe -targetargs:"/nologo /noshadow .\AlgorithmsTests\bin\Debug\AlgorithmsTests.dll" -filter:"+[*]* -[*AlgorithmsTests]*" 
    - .\tools\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i .\results.xml 